### ISSUE TITLE
Compilation Instructions

### ISSUE THREAD

**Issue by bomastudio** [LibreCAD/LibreCAD_3#11]
on Lubuntu 14.10 64bit, following Instructions I get, after the command `cmake ../LibreCAD_3/`, an error

`CMake Error at luacmdinterface/CMakeLists.txt:19 (find_package):`
`  By not providing "FindCurl.cmake" in CMAKE_MODULE_PATH this project has`
`  asked CMake to find a package configuration file provided by "Curl", but`
`  CMake did not find one.`
``
`  Could not find a package configuration file provided by "Curl" with any of`
`  the following names:`
``
`    CurlConfig.cmake`
`    curl-config.cmake`
``
`  Add the installation prefix of "Curl" to CMAKE_PREFIX_PATH or set`
`  "Curl_DIR" to a directory containing one of the above files.  If "Curl"`
`  provides a separate development package or SDK, be sure it has been`
`  installed.`
``
``
`-- Configuring incomplete, errors occurred!`
``
`See also "/home/alessandro/build/CMakeFiles/CMakeOutput.log".`

curl is installed. Any help?

**Comment by gaganjyot** [comment]
Issue has been solved :)

**Comment by gaganjyot** [comment]
@rvt  this issue was solved so can we close it ?

**Comment by outkasst** [comment]
how was this issue solved? i see the same problem on another installation.. can someone explain?
