### ISSUE TITLE
Dimension object size values change when opening previously saved file

### ISSUE THREAD

**Issue by jfirrantello** [LibreCAD/LibreCAD_3#124]
I opened a previously saved DXF created in LibreCAD (saved and re-opened same day) and found that the sizes of a part of the dimensions objects had changed significantly (see image below). Values for items such as text height, arrow size, extension line offset, etc. had changed. I have a hunch that this may have to do with the fact that I had the General Scale set to 50 in the file when everything still was working ok, but am not sure.

**Other info:**
Version: 2.1.3
Compiler: GNU GCC 4.9.1
Compiled on: Sep 23 2016
Qt Version: 5.4.1
Boost Version: 1.60.0
System: Windows 7

![dimensions blow-up example](https://user-images.githubusercontent.com/17624651/31853622-8bd4cd1a-b659-11e7-8456-e0eb24cd6843.PNG)

**Comment by jfirrantello** [comment]
One other comment: It may have reset the **Main drawing unit** when this occurred, unsure.

**Comment by feragon** [comment]
Hi @jfirrantello, this is the repo for the next version of LibreCAD.
You should post your issue here https://github.com/LibreCAD/LibreCAD/issues

**Comment by jfirrantello** [comment]
@feragon Oops, sorry about that. Will do, thanks!
