### ISSUE TITLE
GSoC'2018 wiki page has links to unavaliable content

### ISSUE THREAD

**Issue by Symbian9** [LibreCAD/LibreCAD_3#135]
I just read wiki page ...

- http://wiki.librecad.org/index.php?title=GSoC_2018

... and found that it include **reference link to webpage that not exist anymore**

- http://www.gaganjyot.com/CAD_Plugin_interface

Is it issue of @gaganjyot website or is it incorrect link? Where this page live now?

- http://forum.librecad.org/plugin-interface-for-LibreCAD-3-td5714404.html

P.S.: Is it same content on Medium?

- https://medium.com/@gaganjyot/librecad-v3-b7505883a975

**Comment by rvt** [comment]
The links where from a old student and are ot active anymore.

Is there any specific question you might have?

**Comment by Symbian9** [comment]
> Is there any specific question you might have?

On related forum topic was link to special repo, that at this moment also unavaliable.

> If anyone is interested in standardizing the JSON format for communication between plugin and LibreCAD, that would be of very great help to me.
> 
> https://github.com/gaganjyot/cad_interface
> 
> --
> Thankyou
> Gaganjyot

Was this repo merged in `master` of LibreCAD_3 or this repo sources also lost?

**Comment by feragon** [comment]
This repo was not merged in LibreCAD_3/master, and the link to Medium isn't related to this project.

You can find additional information here : http://forum.librecad.org/GSoC-17-LibreCAD-td5714756.html
