### ISSUE TITLE
Make a proper namespace for all entities within lcviewernoqt

### ISSUE THREAD

**Issue by rvt** [LibreCAD/LibreCAD_3#15]
Current classes are name like : LCDimLinear
What we should create is a proper namespace for it and call the class differently for example
lc::draw::DimLinear

**Comment by gaganjyot** [comment]
LCviewer namespace is created for components under viewer. 

https://github.com/gaganjyot/LibreCAD_3/commit/5111b12945a3720f0b21b8dc40c2ec7896808b34
Should I send a PR?

**Comment by rvt** [comment]
Yes, that's fine

**Comment by gaganjyot** [comment]
:+1:

**Comment by gaganjyot** [comment]
close it?
