### ISSUE TITLE
Dimesions : use <> replacement for the real value

### ISSUE THREAD

**Issue by rvt** [LibreCAD/LibreCAD_3#16]
Currently we just check for <> and substantive the real value.
However what we want is replace <> in the string for the real value

**Comment by gaganjyot** [comment]
A simple example could help much better. This is related to lua AFAIK

**Comment by rvt** [comment]
gaganjyot,

in DXF <> is used as a placeholder for a measured value.
So in a DXF string you can have "my value is <> potatoes" and if the measured value was 10.
The string that was displayed is  "my value is 10 potatoes"

Here is a example: !http://skitch.rvantwisk.nl/~rvt/tmp/Properties-20150219-222609.jpg!
