### ISSUE TITLE
Git master fails to build

### ISSUE THREAD

**Issue by prokoudine** [LibreCAD/LibreCAD_3#188]
Ubuntu 18.10, Git master of LibreCAD_3:

Running 'cmake ..' outputs:

```
CMake Error at persistence/CMakeLists.txt:63 (add_subdirectory):
  The source directory

    /home/alex/soft/cad/LibreCAD_3/persistence/libopencad

  does not contain a CMakeLists.txt file.
```

Is this expected? Should I be able to fix it on my end?

**Comment by feragon** [comment]
libopencad was moved from lcDXFDWG to persistence folder. Try to run 
`git submodule init` and `git submodule update --recursive --remote`

**Comment by prokoudine** [comment]
Yes, that helps! Sent a PR to mention that in the README
