### ISSUE TITLE
Command Line output supports Bold or underscore font?

### ISSUE THREAD

**Issue by Guruprasad-Rane** [LibreCAD/LibreCAD_3#197]
Messages shown on command prompt support any font highlighting? like Bold or  italics or underscore?

**Comment by feragon** [comment]
It doesn't support RTF out of the box.
I tested this and it worked: https://stackoverflow.com/questions/1956542/how-to-make-item-view-render-rich-html-text-in-qt

If you need it, add the delegate to ui->history in lcUI/widgets/clicommand.cpp

**Comment by Guruprasad-Rane** [comment]
I will try this.

**Comment by feragon** [comment]
Use this file for lcUI/widgets/clicommand.cpp: https://gist.github.com/feragon/0790b191c3cc400ba5c4ad2fba54d905 

Try to enter some HTML command to test it (like <b>command</b>)

**Comment by Guruprasad-Rane** [comment]
Yes. It worked perfectly :-)

**Comment by Guruprasad-Rane** [comment]
Couple of issues noticed.

- Line spacing between messages has increased considerably. Tried doc.setDefaultStyleSheet but didn't work. Also tried doc.setDocumentMargin(0); but no sucess.

- Scrollbar get added after few messages and it does not auto scroll. I guess this is because of increased line spacing only.

**Comment by feragon** [comment]
The auto scroll wasn't properly before. You have to scroll down one or two times to enable it.

Can you try to replace the HTMLDelegate sizeHint method with this :
```
QSize HTMLDelegate::sizeHint(const QStyleOptionViewItem& option, const QModelIndex& index) const {
    QTextDocument doc;
    doc.setHtml(option.text);
    doc.setTextWidth(option.rect.width());
    return {(int) doc.textWidth(), (int) doc.size().height()};
}
```

**Comment by Guruprasad-Rane** [comment]
Before changing QSize HTMLDelegate::sizeHint
![before](https://user-images.githubusercontent.com/34202273/49819028-5c4ad880-fd9a-11e8-93ee-49d3939a4a29.png)

After changing QSize HTMLDelegate::sizeHint "Provide Center Point" is almost hidden because of overlap.
![after](https://user-images.githubusercontent.com/34202273/49819068-6ff63f00-fd9a-11e8-9177-69344f2ec2a4.png)


To reduce the line spacing I have tried
```
message("<b>CIRCLE</b><br>Provide Center Point:", self.target_widget)
```

**Comment by feragon** [comment]
Did you tried without the `<br>` ? You can call `message` two times (one call per line)

I'll look at changing sizeHint method to support multi-lines items.

**Comment by Guruprasad-Rane** [comment]
With out <br> with separate `message` calls
![screenshot from 2018-12-13 23-45-33](https://user-images.githubusercontent.com/34202273/49958616-60f5c500-ff31-11e8-894c-99864e619a33.png)

**Comment by Guruprasad-Rane** [comment]
I tried changing ui->history from QListWidget to QTextEdit in readonly mode and I think it works better. Scrollbar appears but it can be made to autoscroll to the last line. Also history need not be trimmed.
![screenshot from 2018-12-15 01-12-56](https://user-images.githubusercontent.com/34202273/50024059-30805a80-0007-11e9-803a-6cc50d7827bb.png)

**Comment by Guruprasad-Rane** [comment]
`history = new QTextEdit(dockWidgetContents);`


```
void CliCommand::write(const QString& message) {
    ui->history->setHtml(ui->history->toHtml() + message);
    ui->history->verticalScrollBar()->setValue(ui->history->verticalScrollBar()->maximum());
}
```

**Comment by Guruprasad-Rane** [comment]
No need for HTML delegate with QTextEdit, it can use toHtml()

**Comment by Guruprasad-Rane** [comment]
Key Up and Key Down event for` CliCommand::onKeyPressed(QKeyEvent *event)` not working.
It has a condition` if(_historyIndex + 1 < _history.size())` but _historyIndex is always -1 and _history.size() is always 0
What is _historyIndex  and _history.size() ? And why this condition?

**Comment by feragon** [comment]
The up and down keys allow to move into the last typed commands.
`_history` should contains every typed command, and `_historyIndex` is the current position in the history.
If `_history.size()` is always 0, that means the commands are not added to the history anymore.
