### ISSUE TITLE
Passing options to command line.

### ISSUE THREAD

**Issue by Guruprasad-Rane** [LibreCAD/LibreCAD_3#198]
Is there any way command line differentiate between text option and command?
For example.
If CIRCLE command is working, it asks for radius. But to change from default Radius to Diameter if we type D or Diameter, command line says "Command diameter not found".

I think modifying  CliCommand::onReturnPressed() can solve this provided it knows that some command is already running or not.
@feragon  Do we have anything to know whether any command is already running?

**Comment by feragon** [comment]
The command line entries are managed in Lua.

Commands are declared here:
https://github.com/LibreCAD/LibreCAD_3/blob/master/lcUILua/ui/commandline.lua#L89-L106

What you need is a text input in the circle creation operation, as you can see in the dimension operations:
https://github.com/LibreCAD/LibreCAD_3/blob/master/lcUILua/createActions/dimradialoperations.lua#L62

Running this command disables the existing commands
