### ISSUE TITLE
Multiple lines in single line command

### ISSUE THREAD

**Issue by Guruprasad-Rane** [LibreCAD/LibreCAD_3#222]
Current line command is able to create a single line. Usually CAD software provide options to create multiple line by typing single command.
An any body guide on how it can be achieved?

**Comment by feragon** [comment]
LibreCAD 3 doesn't support that now, it needs some modifications on the line creation code.

If you need to create a line strip, you could modify this part: https://github.com/LibreCAD/LibreCAD_3/blob/master/lcUILua/createActions/lineoperations.lua#L45

Here, calling `createEntity()` calls `close()` which terminates the current operation. That should be removed and instead update the builder (new ID and startPoint = endPoint). The creation step will stay the same (ask for the 2nd point) so the user will be creating the second line.
