### ISSUE TITLE
Way to access document from LuaScript UI

### ISSUE THREAD

**Issue by rupakbajgain** [LibreCAD/LibreCAD_3#232]
Is there any way to access document via. in luascript widget?
I think it is needed becz. it may be helpful for debugging and other purposes.
I mean to write code like

lineBuilder = lc.builder:LineBuilder()
modify :- lineBuilder
add line to document,

**Comment by feragon** [comment]
Document can be accessed with the `document` global variable.
It is defined here: https://github.com/LibreCAD/LibreCAD_3/blob/master/lcadluascript/lclua.cpp#L72
