### ISSUE TITLE
PPA with nightly builds for Ubuntu/Debian

### ISSUE THREAD

**Issue by Symbian9** [LibreCAD/LibreCAD_3#233]
Is there PPA for test current state of LibreCAD 3, other than build it from source?

**Target platform:** Ubuntu >= 16.04 Xenial; Debian >= 9.x stretch.

**Comment by feragon** [comment]
Currently, no binary distribution is available.

Our CI platform is building LibreCAD 3 from the master branch, maybe it could be pushed to a PPA.

**Comment by Symbian9** [comment]
> maybe it could be pushed to a PPA.

Could you start working on this?
