### ISSUE TITLE
Issue with selecting arc/ellipse

### ISSUE THREAD

**Issue by sckorpio** [LibreCAD/LibreCAD_3#236]
--> Pick arc/ellipse from UI, OK
--> create the arc/ellipse ,OK
--> Click and drag cursor to cover the freshly created arc/ellipse in selection rectangle ,OK
!!! Nothing Happens

**Comment by feragon** [comment]
A new bug was discovered due to wrong detection of intersections between arc and lines.

**Comment by flywire** [comment]
Test with circles too.
