### ISSUE TITLE
Issue compiling in ubuntu

### ISSUE THREAD

**Issue by stormyweathers** [LibreCAD/LibreCAD_3#256]
Hey there,

I'm trying to switch to librecad-3 due to the lua scripting capability.

I managed to install all the dependencies, run `cmake` and `make -j4` without any errors.  But when I try to open the UI, I get the following runtime error.

     cannot open LibreCAD_3/build/lcUI/path.lua: No such file or directory

     Error opening dir: No such file or directory

it seems that `path.lua` is created in `LibreCAD_3/build/bin`, but the executable is in `LibreCAD_3/build/lcUI/`.   putting both files in the same dir fixes this issue.

**Comment by feragon** [comment]
Thanks for the report!
This was already reported in #250. A fix is already available in the `fix-250` branch.
