### ISSUE TITLE
Use Conan package manager for Windows

### ISSUE THREAD

**Issue by feragon** [LibreCAD/LibreCAD_3#263]
Building LibreCAD 3 on Windows is too difficult (confirmed by GCI) and could be simplified by using a package manager.

Conan seems to be the best for our use case : 
- it's easy to set-up (`conan install .`);
- it contains all the required dependencies in `conan-central` and `bincrafters` repos
- it downloads binary packages instead of compiling them (like vcpkg)

**Comment by feragon** [comment]
Fixed with #273

**Comment by Gurren-Joestar** [comment]
![image](https://user-images.githubusercontent.com/71229258/107124613-eefc3a80-6872-11eb-865d-157cda1241bf.png)
i cannot find the option GLEW_ROOT =(
