### ISSUE TITLE
About dialog

### ISSUE THREAD

**Issue by feragon** [LibreCAD/LibreCAD_3#268]
Containing :
- LC3 version
- Git tag
- Machine information (OpenGL...)

**Comment by rupakbajgain** [comment]
i will try it now.

**Comment by flywire** [comment]
Can you include OS info too?

**Comment by rupakbajgain** [comment]
> Can you include OS info too?

Ok, I will try that too.

**Comment by flywire** [comment]
I expect this would often be used to show user config eg in forum. It would be nice if user could copy it and paste it into forum in a collapsed state which need to be clicked to expand. That would save filling forum with seldom needed info.

**Comment by rupakbajgain** [comment]
> 
> 
> I expect this would often be used to show user config eg in forum. It would be nice if user could copy it and paste it into forum in a collapsed state which needed to be clicked to expand. That would save filling forum with seldom needed info.

user config? What information should it contain, it's in html actually.

**Comment by flywire** [comment]
Yes I was thinking of html. I saw it in the html specs somewhere - an element you click and it expands. (I've been looking for it again since I posted above.) It would contain all of the about information but would be pasted into the forum in closed state but could be opened by others when required.

**Comment by rupakbajgain** [comment]
```spoiler Always visible heading
This text won't be visible until the user clicks.
```

**Comment by rupakbajgain** [comment]
<details>
    <summary>Details</summary>
    Something small enough to escape casual notice.
</details>

**Comment by flywire** [comment]
It needs a nice button name so users realise which one to copy to the forum.

Maybe  [Forum copy] or [Copy for forum].

**Comment by rupakbajgain** [comment]
in github html tags work so `<details>` work fine,
but for zulip chat i have to create markdown using `spoiler` formatting help,
ok i will make copy to github or zulip.

**Comment by rupakbajgain** [comment]
@flywire  thanks for the idea.

**Comment by flywire** [comment]
@rupakbajgain could you put sample images and the code behind them in this issue or #324 for reference? I mean the md/html code generated not the C++ code.

**Comment by rupakbajgain** [comment]
@feragon this issue should be closed, i think as i forgot to link it in my PR.
