### ISSUE TITLE
[Help] How to launch LibreCAD 3 on Linux?

### ISSUE THREAD

**Issue by kevinsmia1939** [LibreCAD/LibreCAD_3#282]
I think I successfully compiled LibreCAD 3 on openSUSE Tumbleweed Linux. Which I build a linux package with openSUSE's Open Build Service. https://build.opensuse.org/package/show/home:andythe_great/LibreCAD_3

I'm not sure where the LibreCAD 3 launcher is. How do I start the application? Where is the executable file place at for linux?

Thanks.

**Comment by kevinsmia1939** [comment]
Is there a .desktop file available?

**Comment by feragon** [comment]
When building LibreCAD 3, a bin folder is generated, here you can find 3 executables:
- `librecad`: LC3 GUI
- `luacmdinterface`: the CLI version
- `lcunittest`: unit tests
