### ISSUE TITLE
The entities in toolbar always change positions in each restart.

### ISSUE THREAD

**Issue by rupakbajgain** [LibreCAD/LibreCAD_3#311]
This is problematic since every time i have to search the icon,
![1](https://user-images.githubusercontent.com/37989022/85935360-b75a0700-b90f-11ea-831d-fdd07992594c.png)
![2](https://user-images.githubusercontent.com/37989022/85935363-bb862480-b90f-11ea-9ef9-c1cb518d3eb1.png)

**Comment by feragon** [comment]
@Jedi18  do you know what's happening here?

**Comment by Jedi18** [comment]
Yes, the icons are arranged in the order of loading the lua files, which may be random.
This will be fixed with the customizable toolbar PR in a few days.
