### ISSUE TITLE
Dependency rapidjson should be added to build instructions

### ISSUE THREAD

**Issue by Moult** [LibreCAD/LibreCAD_3#367]
I was following this link https://github.com/LibreCAD/LibreCAD_3/wiki/Building

I then got a build error about rapidjson. I think `rapidjson` needs to be added as a dependency. Can someone confirm?

**Comment by flywire** [comment]
OS details?

**Comment by Moult** [comment]
Gentoo Linux amd64.

**Comment by Jedi18** [comment]
Yes, rapidjson was recently added as a dependency. The wiki needs to be updated.

**Comment by Moult** [comment]
@Jedi18 cheers - I've updated the wiki! Closing issue.

**Comment by flywire** [comment]
`rapidjson` has been added before. Is it updated for all builds?

**Comment by Moult** [comment]
@flywire sorry, I don't understand, did I make a mistake?

**Comment by flywire** [comment]
No, someone [a dev] needs to check build instructions for all platforms.

**Comment by Jedi18** [comment]
@feragon rapidjson is available on Conan. Will adding `rapidjson/1.1.0` to the conanfile.txt be enough to add it?

**Comment by feragon** [comment]
@Jedi18 yes, thanks for checking !
I added it in #369
