### ISSUE TITLE
Is posible compile Librecad_3 using Mingw in Windows 10?

### ISSUE THREAD

**Issue by Gurren-Joestar** [LibreCAD/LibreCAD_3#368]
I know the easy way is installing Visual Studio (>20GB) and dependencies, but i would apreciate if i can compile Librecad_3 with another methods in windows 10.

**Comment by feragon** [comment]
You can try using Windows Subsystem for Linux (and following Ubuntu instructions).
I tested with MinGW/MSYS2 but LibreCAD wasn't working properly. It was 2 years ago so that could have changed.

**Comment by Gurren-Joestar** [comment]
I give up compiling on WSL , now im trying using VS, but i dont know if i had to dowload 36GB of Qt 5.14.2
![image](https://user-images.githubusercontent.com/71229258/107129698-372c5480-6895-11eb-9057-93baae00f492.png)

**Comment by Gurren-Joestar** [comment]
I installed Qt creators, but it doesnt recognize msvc, so im worried why
![image](https://user-images.githubusercontent.com/71229258/107129731-765aa580-6895-11eb-853f-1a1ce0b2faa7.png)

**Comment by Gurren-Joestar** [comment]
Qt recognize msvc compiler, but it doesnt matter because i dont have the qmake.exe for that compiler. Its bad because on the instruccions (set QTDIR=C:\Qt\5.14.1\msvc2017_64) it pointed on a file i dont have
![image](https://user-images.githubusercontent.com/71229258/107129752-b15cd900-6895-11eb-816e-592c09d69575.png)
![image](https://user-images.githubusercontent.com/71229258/107129757-c76a9980-6895-11eb-8156-7b7fb00166e6.png)
