### ISSUE TITLE
Can't open newly created 2D .dxf file

### ISSUE THREAD

**Issue by mcleod777** [LibreCAD/LibreCAD_3#397]
Hi
New to LibreCAD.  I created a very simple 2D drawing using latest version on Windows 10.  Gave it a file name.dxf and saved it to my hard drive.  I tried to re-open the file and it opens and shows that it is open in program but I can't see the drawing.  I also tried to use the import command and still can't see it.  What am I missing? 
Thanks

**Comment by lordofbikes** [comment]
Sure you are using LibreCAD 3?

There may be already solutions in the forum:
https://forum.librecad.org/template/NamlServlet.jtp?macro=search_page&node=4499512&query=empty
A guess is this https://github.com/LibreCAD/LibreCAD/issues/978#issuecomment-475811240
