### ISSUE TITLE
cmake is detecting lua 5.4 instead of 5.3

### ISSUE THREAD

**Issue by GJoe2** [LibreCAD/LibreCAD_3#398]
OS: Manjaro 
```
...
-- Found Lua 5.3 include dir: /usr/include
-- Found Lua 5.3 library: /usr/lib/liblua5.4.so
-- Found Boost: /usr/lib64/cmake/Boost-1.79.0/BoostConfig.cmake (found version "1.79.0") found components: program_options filesystem system log 
-- Configuring done
-- Generating done
```
[logs_librecad.txt](https://github.com/LibreCAD/LibreCAD_3/files/9739837/logs_librecad.txt)

I have many lua versions in my OS, it includes lua 5.4 , 5.3, 5.2
```
$pacman -Q lua                                                                                                             
lua 5.4.4-2
$pacman -Q lua53                                                                                                              
lua53 5.3.6-1
$pacman -Q lua52
lua52 5.2.4-5
```
And only lua 5.2.4 is valid for this project, since it requires Lua >= 5.2 and <= 5.3.5, I am not sure why cmake is trying to choose lua5.3 instead of lua5.2. 

My default lua version is 5.4:
```
$lua
Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio
```

I am not familiar with cmake or c++ stuff, I just want to try Librecad3

**Comment by feragon** [comment]
I updated CMake files to search for Lua 5.3 only. Could you try with the latest master commit?

**Comment by GJoe2** [comment]
The issue is solved with lastest master commit:
```
***** LibreCAD lcadluascript *****
-- Found Eigen3 include dir: /usr/include/eigen3
-- Found Lua: /usr/lib/liblua5.3.so;/usr/lib/libm.so (found suitable exact version "5.3.6")
```
[logs_librecad_2.txt](https://github.com/LibreCAD/LibreCAD_3/files/9793445/logs_librecad_2.txt)
