### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by Questions2000** [LibreCAD/LibreCAD_3#403]
I was just wondering if anyone would be able to tell me what the status of this project is.
Is this project still being worked on?
Has been mentioned for a while now, any ideas of when/if this will be released?
Odd, other than one in December, there really hasn't been any issues reported for almost 2 years?

There was an Appimage of this available in the past, but it was not really functional, the main panel was just solid green background and there were just some toolbars / command line elements.

Has anyone compiled this recently? or are there any new Appimages available for the project?

Anyways, if anyone knows of any information to share.
Thank You

**Comment by lordofbikes** [comment]
There is currently nobody with enough spare time or motivation to work on it.
The GUI is basically for testing the core and features and is far from usable in production.
Have a look at the forum for more information and links to binary packages from our latest GSoC student.
You can take a look if you are still interested, but if you are looking for a usable CAD, stay with V2.
